---
apiVersion: v1
kind: Namespace
metadata:
  name: dummy-pdf-or-png
  labels:
    name: dummy-pdf-or-png
---    
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: dummy-pdf-or-png
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-pdf-or-png-proxy
  namespace: dummy-pdf-or-png
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-pdf-or-png-proxy
  template:
    metadata:
      labels:
        app: dummy-pdf-or-png-proxy 
    spec:
      containers:
      - name: dummy-pdf-or-png-proxy
        image: bobykus/dummy-pdf-or-png-proxy:1.0.6 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3333
        livenessProbe:
          httpGet:
            path: /health
            port: 3333
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3333
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1   
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-pdf-or-png-proxy-service
  namespace: dummy-pdf-or-png
spec:
  type: NodePort
  ports:
  - name: http
    port: 3444
    targetPort: 3333
  selector:
    app: dummy-pdf-or-png-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-pdf-or-png
  namespace: dummy-pdf-or-png
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-pdf-or-png
  template:
    metadata:
      labels:
        app: dummy-pdf-or-png 
    spec:
      containers:
      - name: dummy-pdf-or-png
        image: bobykus/dummy-pdf-or-png:1.0.3 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3030
        livenessProbe:
          httpGet:
            path: /health
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1   
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-pdf-or-png-service
  namespace: dummy-pdf-or-png
spec:
  type: NodePort
  ports:
  - name: http
    port: 3040
    targetPort: 3030
  selector:
    app: dummy-pdf-or-png

